defaultPattern:
  pattern:
    siteswap: 3
    beatDuration: 0.28
    dwellRatio: 0.8
    props: [{type: ball, color: random, radius: 0.05, C: 0.9}]
    dwellPath: (30)(10)
    matchVelocity: false
    dwellCatchScale: 0.06
    dwellTossScale: 0.06
    emptyCatchScale: 0.025
    emptyTossScale: 0.025
    armAngle: 0.3
    jugglers: [{position: {x: 0, z: 0}, rotation: 0, color: green}]
    surfaces: []
    drawHands: false
    useStickFigure: false
    motionBlur: false
    backgroundColor: white
    startingHand: RIGHT
  inputs:
    siteswap: 3
    props: [{type: ball, color: random, radius: 0.05, C: 0.9}]
    dwellPath: (30)(10)
    beatDuration: 0.28
    surfaces: []
examples:
- 
 name: 'Basic example - 5 ball cascade'
 siteswap: '5'
-
 name: 'Vanilla siteswap - 4 ball tower'
 siteswap: '7531'
 beatDuration: '.2'
-
 name: 'Synchronous siteswap - 4 ball sync fountain'
 siteswap: '(4,4)'
-
 name: 'Multiplex siteswap - Gattoplex'
 siteswap: '[54]24'
 drawHands: false
-
 name: 'Passing siteswap - 4 count passing'
 siteswap: '<3|3><3|3><3|3><3P|3P>'
 props:
  - {type: club, color: red, radius: '.05', C: '.97'}
 jugglers:
  - {position: {x: 0, z: 0}, rotation: 0, color: grey}
  - {position: {x: 0, z: -2}, rotation: 3.14, color: grey}
 surfaces: []  
 drawHands: false
-
 name: 'Clubs - 5 club cascade'
 siteswap: '5'
 props:
  - {type: club, color: red, radius: '.05', C: '.97'}
 drawHands: false
-
 name: 'Rings - 6 ring fountain'
 siteswap: '6'
 props:
  - {type: ring, color: red, radius: '.05', C: '.97'}
 drawHands: false
-
 name: 'Dwell path - windmill'
 siteswap: '3'
 dwellRatio: '.7'
 dwellPath: (-20)(20).(20)(-20)
-
 name: 'Dwell path - Mills Mess'
 siteswap: '3'
 dwellRatio: '.8'
 dwellPath: '(2.5,5)(-30,5).(-2.5,-10)(30,-10).(0,-10)(-30,-10)'
-
 name: 'Dwell path - Backcrosses'
 siteswap: '3'
 dwellRatio: '1.4'
 dwellPath: '(30)(10,0,50)'
-
 name: 'Toss/catch modifier - claw'
 siteswap: '3C{C}T{C}'
 emptyTossScale: '.15'
 emptyCatchScale: '.15'
-
 name: 'Catch modifier - penguin'
 siteswap: '3C{P}'
 dwellPath: '(35,-10)(10)'
-
 name: 'Bouncing - lift bounce'
 siteswap: 5B
 dwellPath: (30)(25)
 beatDuration: 0.29
 surfaces: [{position: {x: 0, y: 0, z: 0}, normal: {x: 0, y: 1, z: 0}, scale: 1, color: grey}]
-
 name: 'Bouncing - force bounce'
 siteswap: 5B{F}
 dwellPath: (30)(15)
 beatDuration: 0.26
 surfaces: [{position: {x: 0, y: 0, z: 0}, normal: {x: 0, y: 1, z: 0}, scale: 1, color: grey}]
-
 name: 'Bouncing - hyperlift bounce'
 siteswap: 5B{HL}
 dwellPath: (30)
 beatDuration: 0.4
 surfaces: [{position: {x: 0, y: 0, z: 0}, normal: {x: 0, y: 1, z: 0}, scale: 1, color: grey}]
-
 name: 'Bouncing - hyperforce bounce'
 siteswap: '5B{HF}'
 beatDuration: '.14'
 dwellPath: '(20)(25,-5)'
 matchVelocity: '1'
 surfaces: [{position: {x: 0, y: 0, z: 0}, normal: {x: 0, y: 1, z: 0}, scale: 1, color: grey}]
-
 name: 'Bouncing - custom surface'
 siteswap: 5B
 surfaces: [{position: {x: 0, y: 0, z: 0}, normal: {x: 0, y: 1, z: .25}, scale: 3, color: grey}]
-
 name: 'Bouncing - multiple surfaces'
 siteswap: '7B{HL10}5B{HL11}3155B{HL10}51'
 dwellPath: (25)(10)
 beatDuration: 0.26
 dwellRatio: 0.8
 drawHands: false
 surfaces: [{scale: 2, normal: {x: 0, y: 0, z: 1}, position: {x: 0, y: 2.5, z: 0.5}, color: grey}, {scale: 0.5, normal: {x: 1, y: 0, z: 0}, position: {x: 1, y: 2.5, z: -0.5}, color: grey}]
 props: [{type: ball, color: red, radius: 0.05, C: 0.9}]
-
 name: 'Spin modifier - flats and doubles'
 siteswap: '3S{0}3S{2}'
 props:
  - {type: club, color: red, radius: '.05', C: '.97'}
 drawHands: false
-
 name: 'Dwell modifier - 4 ball sync shower'
 siteswap: '(4xD{.9},4xD{.4})'
 dwellPath: (25)(15).(15)(25)